postgres:
  container_name: demo_postgres
  image: "postgres:latest"
  environment:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    PGDATA: "/data/postgres"
  volumes:
    - postgres:/data/postgres
    - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  ports:
    - "15432:5432"
  restart: unless-stopped